### ISSUE TITLE
可以考虑把语音识别也整合进去呀

### ISSUE THREAD

**Issue by nihui** [Voine/ChatWaifu_Mobile#1]
你好呀，这个聊天器很有意思呢！

推荐一下 https://github.com/k2-fsa/sherpa-ncnn
sherpa-ncnn开源项目，支持移动端实时中英文混合识别，日语识别
把语音识别也整合进去，就不用打字了

qwq

**Comment by triple-Mu** [comment]
蹲一波后续～

**Comment by Voine** [comment]
好，改天研究研究，我才刚上传2分钟，ChatGPT 号就被封勒，悲 :(

**Comment by Rinfair-CSP-A016** [comment]
蹲一蹲

**Comment by IronSublimate** [comment]
插眼~

**Comment by Voine** [comment]
done
