### ISSUE TITLE
我把vits链接的项目的ncnn形式的vits模型下载按照格式创建文件夹使用，加载角色时app显示vits load failed不知道为什么。

### ISSUE THREAD

**Issue by traceyoukkkk** [Voine/ChatWaifu_Mobile#3]

**Comment by Voine** [comment]
你的 vits 文件包含哪些内容呢，我看看

**Comment by traceyoukkkk** [comment]
![image](https://user-images.githubusercontent.com/68846799/222939615-ae5e0a3a-6ab5-4746-bf9c-2b998a4c4c25.png)

**Comment by Voine** [comment]
嗯....看着文件格式好像没有什么问题呢.......要么你发我，我瞅瞅看？

**Comment by traceyoukkkk** [comment]
我就是在你项目转到的那个vits Android的项目里面下载的现成的模型，他那个app我也下过，好像也不起作用，可能是有问题吧🤣

**Comment by Voine** [comment]
你用的是哪个版本的包呢？之前那老哥在读取 bin 文件的地方有一点小问题，我改了一下，不知道你这边用的会不会是老的版本

**Comment by traceyoukkkk** [comment]
我就是release里面下载的，models.zip,

**Comment by Voine** [comment]
我这边下了一下哪个 model.zip ，试了一下里面亚托利的模型，好像是可以用的诶......你试的是哪个

**Comment by traceyoukkkk** [comment]
![Screenshot_2023-03-05-11-45-28-252_com chatwaifu mobile jpg](https://user-images.githubusercontent.com/68846799/222940546-a44e1a28-23e5-44ef-9729-da9ba8d1df8d.jpg)
nay那应该是我的问题了，难道其实是live2d有问题？

**Comment by Voine** [comment]
你的 Live2D 目录的名字，和 VITS 目录的名字都是“亚托莉”嘛？

**Comment by traceyoukkkk** [comment]
是的，我仔细看了下，我下的live2d模型里面的文件格式不完全和你给的结构一致，我再找找live2d模型试试

**Comment by Voine** [comment]
其实只要列表能展示，应该就是找到模型了，你这边多点几次列表 item， 也还是进不去嘛？

**Comment by Voine** [comment]
哎呀，好像是我这边的问题，我再排查一下，果咩果咩

**Comment by Voine** [comment]
好了，外置存储的问题应该修了，亚托莉的模型我直接内置了，下载最新的包就行
