### ISSUE TITLE
Working without translate or use global translate service

### ISSUE THREAD

**Issue by kojdj0811** [Voine/ChatWaifu_Mobile#6]
I can't use this app, because the translate appid and key setting is issue only Chinese.
I was try to the set the option for empty, but the app dose not working.
How about use global translate, like google translator?
Or, please add check box ui for disable translator to input some text that translated Japanese.

**Comment by kojdj0811** [comment]
Oh! I was miss at gpt setting. the issues will closed.
If empty translate edit box, it work without translator.

**Comment by Voine** [comment]
translate switch is add
