### ISSUE TITLE
Possible to add own Live2D and VITS?

### ISSUE THREAD

**Issue by chiakianyka** [Voine/ChatWaifu_Mobile#8]
Hi!
It possible to add own Live2D and VITS?
Thank

**Comment by dsssok** [comment]
> 你好！ 可以添加自己的 Live2D 和 VITS 嗎？ 感謝

可以的，VITS和LIVE本来就是调用方式的！你的VITS在哪里有连接吗？

**Comment by chiakianyka** [comment]
I put on assets/VITSModels/NewFolder and assets/Live2DModels/NewFolder but when I pack the file to apk it can't install.

**Comment by chiakianyka** [comment]
Ok look like I put it in wrong folder sorry
